let employees =[{"id":1,"name":"Garvey","gender":"Male"},
  {"id":2,"name":"Salvidor","gender":"Male"},
  {"id":3,"name":"Lancelot","gender":"Male"},
  {"id":4,"name":"Naoma","gender":"Female"},
  {"id":5,"name":"Bamby","gender":"Female"},
  {"id":6,"name":"Temple","gender":"Male"},
  {"id":7,"name":"Regina","gender":"Female"},
  {"id":8,"name":"Josepha","gender":"Female"},
  {"id":9,"name":"Penn","gender":"Male"},
  {"id":10,"name":"Berti","gender":"Genderfluid"},
  {"id":11,"name":"Cordula","gender":"Non-binary"},
  {"id":12,"name":"Heda","gender":"Female"},
  {"id":13,"name":"Cayla","gender":"Female"},
  {"id":14,"name":"Livvyy","gender":"Genderfluid"},
  {"id":15,"name":"Mara","gender":"Female"},
  {"id":16,"name":"Merrielle","gender":"Female"},
  {"id":17,"name":"Grayce","gender":"Female"},
  {"id":18,"name":"Rafaela","gender":"Female"},
  {"id":19,"name":"Rachele","gender":"Female"},
  {"id":20,"name":"Gibby","gender":"Male"},
  {"id":21,"name":"Taite","gender":"Male"},
  {"id":22,"name":"Chariot","gender":"Male"},
  {"id":23,"name":"Bealle","gender":"Male"},
  {"id":24,"name":"Brandyn","gender":"Male"},
  {"id":25,"name":"Berti","gender":"Female"},
  {"id":26,"name":"Kevyn","gender":"Female"},
  {"id":27,"name":"Baxie","gender":"Male"},
  {"id":28,"name":"Zarah","gender":"Female"},
  {"id":29,"name":"Marita","gender":"Female"},
  {"id":30,"name":"Nolan","gender":"Male"},
  {"id":31,"name":"Raine","gender":"Genderfluid"},
  {"id":32,"name":"Tessa","gender":"Female"},
  {"id":33,"name":"Link","gender":"Non-binary"},
  {"id":34,"name":"Otha","gender":"Female"},
  {"id":35,"name":"Anson","gender":"Male"},
  {"id":36,"name":"Derward","gender":"Male"},
  {"id":37,"name":"Floris","gender":"Female"},
  {"id":38,"name":"Celinka","gender":"Agender"},
  {"id":39,"name":"Tove","gender":"Female"},
  {"id":40,"name":"Jarrad","gender":"Male"},
  {"id":41,"name":"Pepe","gender":"Male"},
  {"id":42,"name":"Jae","gender":"Genderfluid"},
  {"id":43,"name":"Robinet","gender":"Female"},
  {"id":44,"name":"Keven","gender":"Male"},
  {"id":45,"name":"Kennith","gender":"Male"},
  {"id":46,"name":"Norene","gender":"Female"},
  {"id":47,"name":"Gawen","gender":"Male"},
  {"id":48,"name":"Neal","gender":"Male"},
  {"id":49,"name":"Teodoro","gender":"Male"},
  {"id":50,"name":"Kevyn","gender":"Female"}]

  for(user of employees){
    if(user.gender === "Male")
    console.log(`username:${user.name}, usergender:${user.gender}, username:${user.name}`);
  }